---
title: "Is alcohol consumption related to gender and/or GPA?"
author: "Put your name here!"
date: "put the date here"
output: word_document
---

```{r include=FALSE,echo=FALSE}
require(tigerstats)
```

# Introduction


This study is to see if alcohol consumption in the ucdavis1 data set differs by sex and/or GPA. 
1. Do men or women drink more?
2. Is alchol consumption related to GPA?
3. Do 'C' students show an alcohol consumption difference based on gender
4. What about 'A' students?

The ucdavis1 data set is included in the tigerstats package. It is a data frame with 173 observations on 12 variables. It was taken from the text book used at UC Irvine, Mind on Statistics, 4th edition, Uts and Heckard. The variables and descriptions are as follows.
Description

Results of a survey of students at UC-Davis.

* **Sex** a factor with levels Female Male

* **TV** Number of hours spent watching TV per week

* **computer** number of hours spent on computer per week

* **Sleep** hours of sleep per night

* **Seat** a factor with levels Back Front Middle Where do you prefer to sit in class, when you have a choice?

* **alcohol** number of alcoholic drinks consumed per week

* **Height** height in inches

* **momheight** height of mother, in inches

* **dadheight** height of father, in inches

* **exercise** number of hours of exercise per week

* **GPA** grade point average

* **class** a factor with levels LibArts NonLib Student Category: liberal arts or not

Doing a variable analysis shows that the varibles of interest will be

**alcohol**  a numeric variable
**Sex** a factor variable 
and **GPA** a numeric variable that we will need to do further work with in order to answer question pertaining to **A** and **C** students


<In this section you explain what you are trying to show.  Where did the data come from?  What is the research or other question you are trying to answer?>

# Methods

The questions are all somewhat related. Questions 1,3, and 4 are asking the same question, the only difference being the members of the groups the question references: 

* all students
* A students or
* C students

The question deals with a categorical variable (**Sex**) modeling differences in a continuous variable (**alcohol**). 

Question 2 is relating two continuous variables **alcohol** and **GPA** which require regression/correlation techniques.

So our approach will be to deal with all four question in each block of this report.
Boxplots and t-tests for questions 1,3, and 4
scatterplot and regression for question 2.

<Decide on your methods:  use "variable analysis" or other appropriate descriptors.  Make sure to choose at least one graphical method and at least one numerical method.>

#Results

<Divide this section into two sub-sections:  One for your descriptive  results and one for your inferential results.>

## Descriptive Results

### Graphical Descriptive Results

<Graphical results here.  Make sure to show your code.  Provide appropriate labels for axes, giving units if possible, and provide a good title for the graph, too.  Use the graphical results to describe the patterns if any that exist in the data as focused toward the research question>

### Numerical Descriptive Results

<Numerical results go here. Use the numerical results to describe the patterns if any that exist in the data as focused toward the research question>

## Inferential Results

<State hypothesis clearly.  Make sure your discussion of the inferential test covers all the aspects that the test output produces, such as test statistic, p-value etc.  Make a decision about the null hypothesis, explain the assumptions on which the selected test/procedure was based, and why the chosen procedure satisfys the assumptions and is appropriate to answer the research question>


# Discussion and Conclusion

<Discussion and conclusion here.  If you found a relationship be sure to consider whether the relationship occurs because one of the variavbles causes the other, or whether they perhasps are related for some other reason.  Watch the chapter 6 videos from the GeorgeTown videos collection.>
